CREATE DATABASE sheik_database;
show databases;
use sheik_database;
create table USERS(
 ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL, 
AGE INT NOT NULL,
PRIMARY KEY(id)
);
SHOW TABLES;
DESCRIBE USERS;
ALTER TABLE USERS ADD GENDER VARCHAR(10) NOT NULL AFTER AGE;
ALTER TABLE USERS
	ADD CITY VARCHAR(10) NOT NULL,
    ADD CONTACT VARCHAR(50) NOT NULL;
ALTER table USERS MODIFY CONTACT varchar(25) NOT NULL;
ALTER TABLE USERS RENAME TO STUDENTS;

SELECT * FROM STUDENTS;
INSERT INTO STUDENTS VALUES(NULL,'RAM','25','MALE','SALEM','9578312323');
INSERT INTO STUDENTS (NAME,AGE,GENDER,CITY,CONTACT) VALUES ('SAM','23','MALE','MADURAI','9787529888');
DESCRIBE STUDENTS;
INSERT INTO STUDENTS (NAME,AGE,GENDER,CITY,CONTACT) 
VALUES ('SAM','23','MALE','MADURAI','9787529888'),('SAM2','23','MALE','MADURAI','9787529888'),('SAM3','23','MALE','MADURAI','9787529888');

DELETE FROM STUDENTS WHERE ID=3;
UPDATE STUDENTS SET CITY='COIMBATORE', CONTACT='1234567891' WHERE ID=5;